%% Title: Improved Reach Box Script (based on the previous versions)
% Author: Aamir Abbasi
% Box: This script can be used for any reach box. Single script to avoid
% confusion. I have parameterized all the differences across reach boxs in a
% params file. This file will be loaded at initialization of respective reach boxes!

%% Startup setup!
clear all; close all; clc;

% declare global vars
global fh;
global fig_pos;
global currentFile;
global hand;
global stopState;

stopState = 0;
hand = 1;

% add current reach scipt folder to matlab path
currentFile = matlab.desktop.editor.getActiveFilename;
addpath(genpath(fileparts(currentFile)));

%% FIGURE WINDOW
fig_pos=[700 100 534 630];
fh.fig = figure('Position',fig_pos,...
    'MenuBar','none',...
    'NumberTitle','off',...
    'CloseRequestFcn',@fig_close,...
    'Name','NEW REACH BOX GUI');

%% STATUS UPDATE
fh.status = uicontrol(fh.fig,...
    'Style','listbox',...
    'Position',[10 290 230 200],...
    'String',{'Welcome...'},...
    'FontSize',8);

%% RAT ID
fh.NAME_txt = uicontrol(fh.fig,...
    'Style','text',...
    'Position',[35 560 90 40],...
    'String','File Save ID');

set(fh.NAME_txt,'FontSize',12);

fh.NAME = uicontrol(fh.fig,...
    'Style','edit',...
    'Position',[140 570 300 45]);

set(fh.NAME,'String','Ixxx');
set(fh.NAME,'FontSize',20);
set(fh.NAME,'BackgroundColor',[0 0.7 1 ]);

%% Select reach box script
% checkbox for Reach Box 1
fh.cbk1 = uicontrol(fh.fig,...
    'Style','checkbox',...
    'Position',[275 470 90 30],...
    'String','Box 1',...
    'FontSize',12,...
    'Callback',@reachBox1_callback);

% checkbox for Reach Box 2
fh.cbk2 = uicontrol(fh.fig,...
    'Style','checkbox',...
    'Position',[275 440 90 30],...
    'String','Box 2',...
    'FontSize',12,...
    'Callback',@reachBox2_callback);

% checkbox for Reach Box 3
fh.cbk3 = uicontrol(fh.fig,...
    'Style','checkbox',...
    'Position',[275 410 90 30],...
    'String','Box 3',...
    'FontSize',12,...
    'Callback',@reachBox3_callback);

%% PREVIEW CAMERAS
fh.preview = uicontrol(fh.fig,...
    'Style','pushbutton',...
    'String','PREVIEW CAMS',...
    'Position',[375 500 120 30],...
    'Callback',@preview_callback);

%% CALIBRATE ARM MOTOR
fh.calibrate = uicontrol(fh.fig,...
    'Style','pushbutton',...
    'String','CALIBRATE ARM',...
    'Position',[375 440 120 30],...
    'Callback',@calibrateArm_callback);

%% CALIBRATE BACK SENSOR
fh.calibrate = uicontrol(fh.fig,...
    'Style','pushbutton',...
    'String','CALIBRATE BACK',...
    'Position',[375 440 120 30],...
    'Callback',@calibrate_callback);

%% SET ROI
fh.ROI = uicontrol(fh.fig,...
    'Style','pushbutton',...
    'String','SET ROI',...
    'Position',[375 300 120 30],...
    'Callback',@set_ROI);

%% SELECT PROGRAM
prog_options{1}='Sleep Block';
prog_options{2}='Reach Block';
prog_options{3}='Reach Block w/Back';
prog_options{4}='Reach Block no save';
prog_options{5}='Reach Block no save w/Back';
prog_options{6}='Stim with video';
prog_options{7}='Reach Block Basler 2 Cams';

fh.status2 = uicontrol(fh.fig,...
    'Style','listbox',...
    'Position',[15 50 220 130],...
    'String',prog_options,...
    'FontSize',8,...
    'Value',1);

%% NUMBER OF TRIALS
uicontrol(fh.fig,...
    'Style','text',...
    'Position',[15 265 80 15],...
    'String','# Trials');

fh.trials = uicontrol(fh.fig,...
    'Style','edit',...
    'Position',[15 230 80 30]);

set(fh.trials ,'String','100');

%% MINUTES OF SLEEP
uicontrol(fh.fig,...
    'Style','text',...
    'Position',[120 265 100 15],...
    'String','# Minutes Sleep');

fh.sleep = uicontrol(fh.fig,...
    'Style','edit',...
    'Position',[120 230 100 30]);

set(fh.sleep ,'String','120');

%% START/STOP/PAUSE/RESUME BUTTONS
fh.start = uicontrol(fh.fig,...
    'Style','togglebutton',...
    'String','START',...
    'Position',[12 10 45 25],...
    'Callback',@startStop_callback);

fh.pause = uicontrol(fh.fig,...
    'Style','togglebutton',...
    'String','PAUSE',...
    'Position',[57 10 45 25],...
    'Callback',@pause_callback);

%% OPEN/CLOSE DOOR BUTTONS
fh.doorOpen = uicontrol(fh.fig,...
    'Style','pushbutton',...
    'String','OPEN',...
    'Position',[102 10 45 25],...
    'Callback',@doorOpen_callback);

fh.doorClose = uicontrol(fh.fig,...
    'Style','pushbutton',...
    'String','CLOSE',...
    'Position',[147 10 45 25],...
    'Callback',@doorClose_callback);

%% DISPENSE PELLET BUTTON
fh.dispense = uicontrol(fh.fig,...
    'Style','pushbutton',...
    'String','PELLET',...
    'Position',[192 10 45 25],...
    'Callback',@pellet_callback);

%% INTERTRIAL DELAY
uicontrol(fh.fig,...
    'Style','text',...
    'Position',[50 210 80 15],...
    'String','ITI Delay:');
fh.Iti = uicontrol(fh.fig,'Style','edit',...
    'Position',[135 210 40 15]);
set(fh.Iti ,'String','10');

%% DOOR OPEN TIME
uicontrol(fh.fig,'Style','text',...
    'Position',[50 190 80 15],...
    'String','Door Open:');
fh.doorWait = uicontrol(fh.fig,'Style','edit',...
    'Position',[135 190 40 15]);
set(fh.doorWait ,'String','15');

% %% COUNTER
% fh.tick=uicontrol(fh.fig,...
%     'Style','text',...
%     'Position',[345 120 120 30],...
%     'String','0','FontSize',20);

%% PELLET LOCATION
fh.pelLoc = uicontrol(fh.fig,...
    'Style','pushbutton',...
    'Position',[60 500 120 50],...
    'String','R Handed Rat',...
    'BackgroundColor',[0.2 1 0.2],...
    'FontSize',12,...
    'Callback',@pelLoc_callback);

%% EOF
